// Ports upstream tests/security/test_anonymization_shapes.py and the response-shape cases of test_anonymization_endpoints.py.
// Expected pseudonyms and redacted strings were generated by running the upstream Python module.
import { describe, expect, it } from 'vitest';

import {
  AMBIGUOUS_IDENTITY_FIELDS,
  EMAIL_SHAPED_FIELDS,
  FREE_TEXT_FIELDS,
  FREE_TEXT_REDACTIONS,
  IDENTITY_FIELDS,
  KNOWN_DATA_TYPES,
  NON_USER_MARKER_FIELDS,
  NULL_FIELDS,
  PLACEHOLDERS,
  STRICT_IDENTITY_FIELDS,
  USER_CONTAINER_KEYS,
  USER_ID_KEYS,
  USER_ONLY_NULL_FIELDS,
  USER_SIGNAL_FIELDS,
  anonymizeResponse,
  anonymizeResponseData,
  generateAnonymousId,
  scrubFreeText,
  scrubIdentity,
} from '../../src/core/anonymization';
import type { PseudonymOptions } from '../../src/core/anonymization';
import { tierForPath } from '../../src/core/anonymization-tiers';
import type { AnonymizationTier } from '../../src/types';

// Fixtures are deliberately loose: the scrubber changes value types (a name
// becomes null, an attachment list becomes a string).
type Json = any;

/** A fresh per-request pseudonym context, unsalted like upstream. */
function fresh(salt: string | null = null): PseudonymOptions {
  return { salt, memo: new Map() };
}

/** Upstream's `_anonymize_for_endpoint`: tier from the path, then that tier's treatment. */
function anonymizeForEndpoint(data: Json, path: string): { result: Json; tier: AnonymizationTier } {
  const tier = tierForPath(path);
  return { result: anonymizeResponse(data, { tier, path, ...fresh() }), tier };
}

// Sentinels that must never survive anonymization, in any nesting position.
const SENTINELS = ['jdoe2', 'Bob Smith', 'Alice Example', '@illinois.edu', '670001234', 'Doe, John'];

function expectNoPii(payload: unknown): void {
  const blob = JSON.stringify(payload);
  for (const sentinel of SENTINELS) {
    expect(blob, `PII leaked: ${sentinel}`).not.toContain(sentinel);
  }
}

/** Flatten a payload into { path: sorted keys } for key-set comparison. */
function collectKeySets(node: unknown, path = '$', found: Record<string, string[]> = {}): Record<string, string[]> {
  if (Array.isArray(node)) {
    node.forEach((item, index) => collectKeySets(item, `${path}[${index}]`, found));
  } else if (typeof node === 'object' && node !== null) {
    found[path] = Object.keys(node).sort();
    for (const [key, value] of Object.entries(node)) {
      collectKeySets(value, `${path}.${key}`, found);
    }
  }
  return found;
}

// ---------------------------------------------------------------------------
// Fixtures modelled on real Canvas responses
// ---------------------------------------------------------------------------

/** GET /courses/{id}/users?include[]=enrollments&include[]=email */
function usersWithEnrollments(): Json {
  return [
    {
      id: 101,
      name: 'John Doe',
      sortable_name: 'Doe, John',
      short_name: 'John',
      login_id: 'jdoe2',
      email: 'jdoe2@illinois.edu',
      sis_user_id: '670001234',
      avatar_url: 'https://canvas.example.edu/images/jdoe2.png',
      enrollments: [
        {
          id: 9001,
          user_id: 101,
          course_id: 55,
          type: 'StudentEnrollment',
          sis_user_id: '670001234',
          html_url: 'https://canvas.example.edu/courses/55/users/101',
          user: { id: 101, name: 'John Doe', login_id: 'jdoe2' },
        },
      ],
    },
  ];
}

/** GET .../submissions?include[]=submission_comments */
function submissionsWithComments(): Json {
  return [
    {
      id: 7001,
      user_id: 101,
      assignment_id: 42,
      submitted_at: '2026-03-01T12:00:00Z',
      body: 'My essay, by John Doe',
      submission_comments: [
        {
          id: 3001,
          author_id: 202,
          author_name: 'Bob Smith',
          comment: 'Nice work! Ping me at bob@illinois.edu or 217-555-0134.',
          avatar_path: '/images/thumbnails/bob.png',
          author: {
            id: 202,
            display_name: 'Bob Smith',
            avatar_image_url: 'https://canvas.example.edu/bob.png',
            html_url: 'https://canvas.example.edu/courses/55/users/202',
          },
        },
      ],
    },
  ];
}

/** GET .../submissions/{user_id}?include[]=full_rubric_assessment */
function rubricAssessmentSubmission(): Json {
  return {
    id: 7002,
    user_id: 101,
    submitted_at: '2026-03-01T12:00:00Z',
    full_rubric_assessment: {
      id: 5001,
      assessor_id: 202,
      assessor_name: 'Bob Smith',
      assessment_type: 'peer_review',
      assessor: { id: 202, display_name: 'Bob Smith', avatar_image_url: 'https://canvas.example.edu/bob.png' },
      data: [{ criterion_id: '_1234', points: 4, comments: 'Great thesis - reach me at bob@illinois.edu' }],
    },
  };
}

/** GET /users/{id}/profile: every email-bearing key Canvas returns on a profile. */
function selfProfile(): Json {
  return {
    id: 101,
    name: 'John Doe',
    short_name: 'John',
    sortable_name: 'Doe, John',
    full_name: 'John Doe',
    login_id: 'jdoe2',
    primary_email: 'jdoe2@illinois.edu',
    unconfirmed_email: 'jdoe2@illinois.edu',
    contact_info: 'jdoe2@illinois.edu',
    integration_id: '670001234',
    pronouns: 'he/him',
    pronunciation: 'JON DOH',
    bio: 'Reach me at jdoe2@illinois.edu',
    time_zone: 'America/Chicago',
    locale: 'en',
    avatar_url: 'https://canvas.example.edu/images/jdoe2.png',
    calendar: { ics: 'https://canvas.example.edu/feeds/users/x.ics' },
    communication_channels: [
      { id: 1, type: 'email', address: 'jdoe2@illinois.edu', position: 1 },
      { id: 2, type: 'sms', address: '12175550134', position: 2 },
    ],
    pseudonyms: [{ id: 3, account_id: 1, unique_id: 'jdoe2@illinois.edu' }],
  };
}

/** GET /conversations */
function conversationsList(): Json {
  return [
    {
      id: 6001,
      subject: 'Extension request',
      workflow_state: 'unread',
      last_message: 'Hi prof, reach me at jdoe2@illinois.edu or 217-555-0134.',
      last_authored_message: 'Sure - see you at office hours.',
      participants: [
        { id: 101, name: 'John Doe', full_name: 'John Doe', pronouns: 'he/him', avatar_url: 'https://canvas/avatars/101' },
        { id: 202, name: 'Carol Cee', full_name: 'Carol Cee', pronouns: null },
      ],
      messages: [{ id: 8001, author_id: 101, body: 'Long version, reply to jdoe2@illinois.edu' }],
    },
  ];
}

/** GET /courses/{id}/pages?include[]=body */
function pagesList(): Json {
  return [
    {
      page_id: 5001,
      url: 'week-1-overview',
      title: 'Week 1 Overview',
      published: true,
      body: '<p>Office hours Tue 2-4. Email me at prof@illinois.edu.</p>',
      last_edited_by: {
        id: 303,
        display_name: 'Alice Example',
        avatar_image_url: 'https://canvas/avatars/303',
        html_url: 'https://canvas/courses/55/users/303',
      },
    },
  ];
}

/** GET /courses/{id}/discussion_topics/{id}/view */
function discussionView(): Json {
  return {
    unread_entries: [],
    participants: [
      { id: 101, display_name: 'Alice Student', avatar_image_url: 'http://x/a.png' },
      { id: 102, display_name: 'Bob Learner', avatar_image_url: 'http://x/b.png' },
    ],
    view: [
      {
        id: 1,
        user_id: 101,
        user_name: 'Alice Student',
        message: 'My email is alice@example.com',
        replies: [{ id: 2, user_id: 102, user_name: 'Bob Learner', message: 'Hi Alice' }],
      },
    ],
    new_entries: [{ id: 3, user_id: 102, user_name: 'Bob Learner', message: 'A new post' }],
  };
}

const ALL_FIXTURES: Record<string, () => Json> = {
  rubric_assessment_submission: rubricAssessmentSubmission,
  self_profile: selfProfile,
  submissions_with_comments: submissionsWithComments,
  users_with_enrollments: usersWithEnrollments,
};
const FIXTURE_NAMES = Object.keys(ALL_FIXTURES);

function fixture(name: string): Json {
  const build = ALL_FIXTURES[name];
  if (build === undefined) {
    throw new Error(`unknown fixture ${name}`);
  }
  return build();
}

// ---------------------------------------------------------------------------
// Field policy tables
// ---------------------------------------------------------------------------

describe('field policy tables match upstream', () => {
  const sorted = (values: Iterable<string>): string[] => [...values].sort();

  it('lists the same fields', () => {
    expect(sorted(STRICT_IDENTITY_FIELDS)).toEqual(
      sorted([
        'short_name',
        'sortable_name',
        'user_name',
        'author_name',
        'assessor_name',
        'grader_name',
        'email',
        'primary_email',
        'unconfirmed_email',
        'contact_info',
        'login_id',
      ]),
    );
    expect(sorted(EMAIL_SHAPED_FIELDS)).toEqual(sorted(['email', 'primary_email', 'unconfirmed_email', 'contact_info']));
    expect(sorted(AMBIGUOUS_IDENTITY_FIELDS)).toEqual(sorted(['name', 'display_name', 'full_name', 'unique_id']));
    expect(sorted(IDENTITY_FIELDS)).toEqual(sorted([...STRICT_IDENTITY_FIELDS, ...AMBIGUOUS_IDENTITY_FIELDS]));
    expect(sorted(NULL_FIELDS)).toEqual(
      sorted([
        'sis_user_id',
        'integration_id',
        'sis_login_id',
        'avatar_url',
        'avatar_image_url',
        'bio',
        'pronouns',
        'pronunciation',
      ]),
    );
    expect(sorted(USER_ONLY_NULL_FIELDS)).toEqual(['address', 'locale', 'time_zone']);
    expect(USER_ID_KEYS).toEqual(['user_id', 'author_id', 'assessor_id', 'grader_id']);
    expect(sorted(USER_SIGNAL_FIELDS)).toEqual(
      sorted([
        'sortable_name',
        'short_name',
        'login_id',
        'email',
        'sis_user_id',
        'sis_login_id',
        'avatar_url',
        'avatar_image_url',
        'enrollments',
      ]),
    );
    expect(sorted(NON_USER_MARKER_FIELDS)).toEqual(['course_code', 'enrollment_term_id', 'sis_course_id']);
    expect(sorted(USER_CONTAINER_KEYS)).toEqual(
      sorted([
        'user',
        'author',
        'assessor',
        'grader',
        'editor',
        'submitter',
        'participant',
        'student',
        'observed_user',
        'communication_channels',
        'pseudonyms',
      ]),
    );
    expect(sorted(FREE_TEXT_FIELDS)).toEqual(
      sorted(['message', 'comment', 'comments', 'body', 'last_message', 'last_authored_message']),
    );
    expect(sorted(KNOWN_DATA_TYPES)).toEqual(['assignments', 'discussions', 'submissions', 'users']);
  });

  it('keeps the placeholder strings verbatim', () => {
    expect(PLACEHOLDERS).toEqual({
      ssn: '[SSN_REDACTED]',
      email: '[EMAIL_REDACTED]',
      phone: '[PHONE_REDACTED]',
      redacted: '[REDACTED]',
      content: '[CONTENT_REDACTED]',
      longDescription: '[LONG_DESCRIPTION_REDACTED_FOR_PRIVACY]',
      emailDomain: '@example.edu',
    });
  });

  it('redacts SSN, then email, then phone', () => {
    expect(FREE_TEXT_REDACTIONS.map((step) => [step.kind, step.placeholder])).toEqual([
      ['ssn', '[SSN_REDACTED]'],
      ['email', '[EMAIL_REDACTED]'],
      ['phone', '[PHONE_REDACTED]'],
    ]);
  });
});

// ---------------------------------------------------------------------------
// Pseudonyms
// ---------------------------------------------------------------------------

describe('generateAnonymousId', () => {
  it('matches upstream byte for byte when unsalted', () => {
    // hashlib.sha256(b"12345").hexdigest()[:8] == "5994471a"
    expect(generateAnonymousId(12345, 'Student', fresh())).toBe('Student_5994471a');
    expect(generateAnonymousId(101, 'Student', fresh())).toBe('Student_16dc368a');
    expect(generateAnonymousId(202, 'Student', fresh())).toBe('Student_c17edaae');
    expect(generateAnonymousId(0, 'Student', fresh())).toBe('Student_5feceb66');
    expect(generateAnonymousId('abc', 'Student', fresh())).toBe('Student_ba7816bf');
  });

  it('hashes the decimal string, so a numeric and a string id agree', () => {
    expect(generateAnonymousId('101', 'Student', fresh())).toBe(generateAnonymousId(101, 'Student', fresh()));
    expect(generateAnonymousId(101n, 'Student', fresh())).toBe('Student_16dc368a');
  });

  it('renders non-numeric ids the way Python str() does', () => {
    // hashlib.sha256(b"None") / b"True" / b"False"
    expect(generateAnonymousId(null, 'Student', fresh())).toBe('Student_dc937b59');
    expect(generateAnonymousId(undefined, 'Student', fresh())).toBe('Student_dc937b59');
    expect(generateAnonymousId(true, 'Student', fresh())).toBe('Student_3cbc87c7');
    expect(generateAnonymousId(false, 'Student', fresh())).toBe('Student_60a33e6c');
    expect(generateAnonymousId('sis:é', 'Student', fresh())).toBe('Student_522d9746');
  });

  it('switches to HMAC-SHA256 when a salt is given', () => {
    // hmac.new(b"pepper", b"12345", hashlib.sha256).hexdigest()[:8] == "e8b28b17"
    expect(generateAnonymousId(12345, 'Student', fresh('pepper'))).toBe('Student_e8b28b17');
    expect(generateAnonymousId(101, 'Student', fresh('pepper'))).toBe('Student_a3f1a1b9');
    expect(generateAnonymousId(101, 'Student', fresh('other salt'))).not.toBe('Student_a3f1a1b9');
  });

  it('treats an empty salt as no salt', () => {
    expect(generateAnonymousId(12345, 'Student', fresh(''))).toBe('Student_5994471a');
  });

  it('keeps prefixes apart in the memo (upstream collapses them)', () => {
    const pseudonyms = fresh();
    expect(generateAnonymousId(202, 'Student', pseudonyms)).toBe('Student_c17edaae');
    expect(generateAnonymousId(202, 'Reviewer', pseudonyms)).toBe('Reviewer_c17edaae');
    expect(generateAnonymousId(202, 'Reviewee', pseudonyms)).toBe('Reviewee_c17edaae');
    expect(generateAnonymousId(202, 'Student', pseudonyms)).toBe('Student_c17edaae');
    expect([...pseudonyms.memo.keys()]).toEqual(['Student:202', 'Reviewer:202', 'Reviewee:202']);
  });

  it('reads the memo before hashing', () => {
    const pseudonyms = fresh();
    pseudonyms.memo.set('Student:7', 'Student_from_memo');
    expect(generateAnonymousId(7, 'Student', pseudonyms)).toBe('Student_from_memo');
  });

  it('keeps no state outside the memo it is given', () => {
    const first = fresh('pepper');
    generateAnonymousId(101, 'Student', first);
    expect(first.memo.size).toBe(1);

    // A later request with a different salt must not see the first one's result.
    const second = fresh();
    expect(generateAnonymousId(101, 'Student', second)).toBe('Student_16dc368a');
    expect([...second.memo.keys()]).toEqual(['Student:101']);
  });

  it('gives different students different pseudonyms', () => {
    expect(generateAnonymousId(202, 'Student', fresh())).not.toBe(generateAnonymousId(101, 'Student', fresh()));
  });
});

// ---------------------------------------------------------------------------
// Free-text redaction
// ---------------------------------------------------------------------------

describe('scrubFreeText', () => {
  // [input, upstream scrub_free_text(input)]
  const PYTHON_CASES: Array<[string, string]> = [
    ['Nice work! Ping me at bob@illinois.edu or 217-555-0134.', 'Nice work! Ping me at [EMAIL_REDACTED] or [PHONE_REDACTED].'],
    ['SSN 123-45-6789 on file', 'SSN [SSN_REDACTED] on file'],
    ['call 2175550134 or 217.555.0134 or 217-555.0134', 'call [PHONE_REDACTED] or [PHONE_REDACTED] or [PHONE_REDACTED]'],
    ['12175550134', '12175550134'],
    ['x123-45-6789', 'x123-45-6789'],
    ['123-45-67890', '123-45-67890'],
    ['mail .foo@bar.com now', 'mail .[EMAIL_REDACTED] now'],
    ['a@b.com.x@y.org', '[EMAIL_REDACTED][EMAIL_REDACTED]'],
    ['first.last+tag@sub.example.co.uk,', '[EMAIL_REDACTED],'],
    ['user@host', 'user@host'],
    ['user@host.c', 'user@host.c'],
    ['user@host.com1', 'user@host.com1'],
    ['jdoe2@illinois.edu123-45-6789', 'jdoe2@illinois.edu123-45-6789'],
    ['123-45-6789@x.com', '[SSN_REDACTED]@x.com'],
    ['a@b.co 555-123-4567 999-88-7777 c_d@e.org', '[EMAIL_REDACTED] [PHONE_REDACTED] [SSN_REDACTED] [EMAIL_REDACTED]'],
    ['_under@score.com', '[EMAIL_REDACTED]'],
    ['', ''],
  ];

  it.each(PYTHON_CASES)('%j', (input, expected) => {
    expect(scrubFreeText(input)).toBe(expected);
  });

  describe('Unicode digits and word boundaries (Python \\d and \\b are Unicode-aware)', () => {
    const UNICODE_CASES: Array<[string, string, string]> = [
      ['full-width SSN', '１２３-４５-６７８９', '[SSN_REDACTED]'],
      ['Arabic-Indic phone', '٢١٧-٥٥٥-٠١٣٤', '[PHONE_REDACTED]'],
      ['full-width phone without separators', '２１７５５５０１３４', '[PHONE_REDACTED]'],
      ['Extended Arabic-Indic SSN and mixed-script phone', '۱۲۳-۴۵-۶۷۸۹ and 217٥٥٥0134', '[SSN_REDACTED] and [PHONE_REDACTED]'],
      ['a non-ASCII letter before digits is not a boundary', 'é123-45-6789', 'é123-45-6789'],
      ['a non-ASCII letter before an email start is not a boundary', 'éfoo.bar@x.com', 'éfoo[EMAIL_REDACTED]'],
      ['a non-ASCII letter after the TLD blocks the match', 'user@host.comé', 'user@host.comé'],
      ['a symbol before digits is a boundary', '№217-555-0134', '№[PHONE_REDACTED]'],
      ['a superscript digit before digits is a word character', '²217-555-0134', '²217-555-0134'],
      ['a superscript digit after digits is a word character', '217-555-0134²', '217-555-0134²'],
    ];

    it.each(UNICODE_CASES)('%s', (_label, input, expected) => {
      expect(scrubFreeText(input)).toBe(expected);
    });

    it('redacts astral-plane decimal digits', () => {
      // MATHEMATICAL BOLD DIGITS, outside the BMP.
      expect(scrubFreeText('call 𝟐𝟏𝟕-𝟓𝟓𝟓-𝟎𝟏𝟑𝟒 now')).toBe('call [PHONE_REDACTED] now');
      expect(scrubFreeText('😀217-555-0134😀')).toBe('😀[PHONE_REDACTED]😀');
    });
  });

  it('passes non-strings through untouched', () => {
    expect(scrubFreeText(null)).toBeNull();
    expect(scrubFreeText(42)).toBe(42);
    const list = ['a@b.com'];
    expect(scrubFreeText(list)).toBe(list);
  });

  it('is idempotent', () => {
    for (const [input] of PYTHON_CASES) {
      const once = scrubFreeText(input);
      expect(scrubFreeText(once)).toBe(once);
    }
  });

  it('agrees with a plain left-to-right regex replace of the three patterns', () => {
    // The email pass is a hand-written linear scan; this pins it to the
    // pattern it claims to implement.
    const steps = FREE_TEXT_REDACTIONS.map((step) => ({
      pattern: new RegExp(step.source, 'gu'),
      placeholder: step.placeholder,
    }));
    const reference = (text: string): string =>
      steps.reduce((current, step) => current.replace(step.pattern, step.placeholder), text);

    const tokens = [
      'a.b', 'jdoe2', '@', '@', 'x.com', 'illinois.edu', '.org', '.c', '.co1', '123', '45', '6789', '555', '0134',
      '217', '-', '-', '.', '.', ' ', ' ', 'é', '１２３', '４５', '６７８９', '٠١٢', '٣٤٥٦', '_', '%', '+', ',', '😀',
      'ü', 'COM', '9', 'x', '\n', '[', ']', ':', '/', '𝟏𝟐𝟑', '²',
    ];
    let seed = 0x1234567;
    const random = (): number => {
      seed ^= seed << 13;
      seed >>>= 0;
      seed ^= seed >>> 17;
      seed ^= seed << 5;
      seed >>>= 0;
      return seed / 0x100000000;
    };

    let redacted = 0;
    for (let i = 0; i < 20000; i += 1) {
      const length = 1 + Math.floor(random() * 12);
      let text = '';
      for (let j = 0; j < length; j += 1) {
        text += tokens[Math.floor(random() * tokens.length)];
      }
      const expected = reference(text);
      if (expected !== text) {
        redacted += 1;
      }
      expect(scrubFreeText(text)).toBe(expected);
    }
    // Guard against a generator that never produces a match.
    expect(redacted).toBeGreaterThan(100);
  });

  it('stays linear on a long run of local-part characters', () => {
    // A plain global regex retries from every "." here and takes minutes.
    const hostile = `${'a.'.repeat(150_000)} @ ${'a.'.repeat(150_000)}@`;
    const started = performance.now();
    expect(scrubFreeText(hostile)).toBe(hostile);
    expect(performance.now() - started).toBeLessThan(2000);
  });
});

// ---------------------------------------------------------------------------
// Byte-for-byte parity with upstream on the fixture payloads
// ---------------------------------------------------------------------------

describe('output parity with upstream', () => {
  it('roster with nested enrollments (full tier, users)', () => {
    const { result, tier } = anonymizeForEndpoint(usersWithEnrollments(), '/courses/55/users');
    expect(tier).toBe('full');
    expect(result).toEqual([
      {
        id: 101,
        name: 'Student_16dc368a',
        sortable_name: 'Student_16dc368a',
        short_name: 'Student_16dc368a',
        login_id: 'student_16dc368a',
        email: 'student_16dc368a@example.edu',
        sis_user_id: null,
        avatar_url: null,
        enrollments: [
          {
            id: 9001,
            user_id: 101,
            course_id: 55,
            type: 'StudentEnrollment',
            sis_user_id: null,
            html_url: 'https://canvas.example.edu/courses/55/users/101',
            user: { id: 101, name: 'Student_16dc368a', login_id: 'student_16dc368a' },
          },
        ],
      },
    ]);
  });

  it('submissions with comments (full tier, submissions)', () => {
    const { result } = anonymizeForEndpoint(submissionsWithComments(), '/courses/55/assignments/42/submissions');
    expect(result).toEqual([
      {
        id: 7001,
        user_id: 101,
        assignment_id: 42,
        submitted_at: '2026-03-01T12:00:00Z',
        body: '[CONTENT_REDACTED_FOR_Student_16dc368a]',
        submission_comments: [
          {
            id: 3001,
            author_id: 202,
            author_name: 'Student_c17edaae',
            comment: 'Nice work! Ping me at [EMAIL_REDACTED] or [PHONE_REDACTED].',
            avatar_path: null,
            author: {
              id: 202,
              display_name: 'Student_c17edaae',
              avatar_image_url: null,
              html_url: 'https://canvas.example.edu/courses/55/users/202',
            },
          },
        ],
      },
    ]);
  });

  it('rubric assessment (full tier, submissions)', () => {
    const { result } = anonymizeForEndpoint(rubricAssessmentSubmission(), '/courses/55/assignments/42/submissions/101');
    expect(result).toEqual({
      id: 7002,
      user_id: 101,
      submitted_at: '2026-03-01T12:00:00Z',
      full_rubric_assessment: {
        id: 5001,
        assessor_id: 202,
        assessor_name: 'Student_c17edaae',
        assessment_type: 'peer_review',
        assessor: { id: 202, display_name: 'Student_c17edaae', avatar_image_url: null },
        data: [{ criterion_id: '_1234', points: 4, comments: 'Great thesis - reach me at [EMAIL_REDACTED]' }],
      },
    });
  });

  it('another user’s profile (full tier, users)', () => {
    const { result } = anonymizeForEndpoint(selfProfile(), '/users/456/profile');
    expect(result).toEqual({
      id: 101,
      name: 'Student_16dc368a',
      short_name: 'Student_16dc368a',
      sortable_name: 'Student_16dc368a',
      full_name: 'Student_16dc368a',
      login_id: 'student_16dc368a',
      primary_email: 'student_16dc368a@example.edu',
      unconfirmed_email: 'student_16dc368a@example.edu',
      contact_info: 'student_16dc368a@example.edu',
      integration_id: null,
      pronouns: null,
      pronunciation: null,
      bio: null,
      time_zone: null,
      locale: null,
      avatar_url: null,
      calendar: { ics: 'https://canvas.example.edu/feeds/users/x.ics' },
      communication_channels: [
        { id: 1, type: 'email', address: null, position: 1 },
        { id: 2, type: 'sms', address: null, position: 2 },
      ],
      // Keyed to the pseudonym record's own id (3), as upstream does.
      pseudonyms: [{ id: 3, account_id: 1, unique_id: 'Student_4e074085' }],
    });
  });

  it('conversations (free_text tier)', () => {
    const { result, tier } = anonymizeForEndpoint(conversationsList(), '/conversations');
    expect(tier).toBe('free_text');
    expect(result).toEqual([
      {
        id: 6001,
        subject: 'Extension request',
        workflow_state: 'unread',
        last_message: 'Hi prof, reach me at [EMAIL_REDACTED] or [PHONE_REDACTED].',
        last_authored_message: 'Sure - see you at office hours.',
        participants: [
          { id: 101, name: 'John Doe', full_name: 'John Doe', pronouns: null, avatar_url: null },
          { id: 202, name: 'Carol Cee', full_name: 'Carol Cee', pronouns: null },
        ],
        messages: [{ id: 8001, author_id: 101, body: 'Long version, reply to [EMAIL_REDACTED]' }],
      },
    ]);
  });

  it('pages (identity tier)', () => {
    const { result, tier } = anonymizeForEndpoint(pagesList(), '/courses/55/pages');
    expect(tier).toBe('identity');
    expect(result).toEqual([
      {
        page_id: 5001,
        url: 'week-1-overview',
        title: 'Week 1 Overview',
        published: true,
        body: '<p>Office hours Tue 2-4. Email me at prof@illinois.edu.</p>',
        last_edited_by: {
          id: 303,
          display_name: 'Student_8bd9c0d4',
          avatar_image_url: null,
          html_url: 'https://canvas/courses/55/users/303',
        },
      },
    ]);
  });

  it.each<[string, Json, Json]>([
    ['id 0 is a real id', { id: 0, login_id: 'x' }, { id: 0, login_id: 'student_5feceb66' }],
    [
      'no id anywhere falls back to [REDACTED]',
      { user: { name: 'John Doe', email: 'j@x.edu', login_id: 'jd' } },
      { user: { name: '[REDACTED]', email: '[REDACTED]', login_id: '[REDACTED]' } },
    ],
    [
      'keys match case-insensitively, user signals do not',
      { id: 5, Sortable_Name: 'Doe, John', EMAIL: 'a@b.com', Avatar_URL: 'http://x', Body: 'mail a@b.com' },
      { id: 5, Sortable_Name: '[REDACTED]', EMAIL: '[REDACTED]', Avatar_URL: null, Body: 'mail [EMAIL_REDACTED]' },
    ],
    [
      'mixed-case keys keyed to user_id',
      { id: 5, user_id: 9, Sortable_Name: 'Doe, John', EMAIL: 'a@b.com', Login_ID: 'JD', Name: 'J' },
      {
        id: 5,
        user_id: 9,
        Sortable_Name: 'Student_19581e27',
        EMAIL: 'student_19581e27@example.edu',
        Login_ID: 'student_19581e27',
        Name: 'Student_19581e27',
      },
    ],
    [
      'non-string identity values are replaced too',
      { id: 1, login_id: 'x', name: { first: 'A' }, email: 5 },
      { id: 1, login_id: 'student_6b86b273', name: 'Student_6b86b273', email: 'student_6b86b273@example.edu' },
    ],
    [
      'null and empty identity values are preserved',
      { id: 1, login_id: '', email: null, name: '', sortable_name: 'D, J' },
      { id: 1, login_id: '', email: null, name: '', sortable_name: 'Student_6b86b273' },
    ],
    [
      'a bare-string user container without an id',
      { title: 't', author: 'Bob Smith' },
      { title: 't', author: '[REDACTED]' },
    ],
    [
      'a nested record inherits the enclosing user id',
      { id: 77, user_id: 101, meta: { display_name: 'John Doe', short_name: 'John' } },
      { id: 77, user_id: 101, meta: { display_name: 'Student_16dc368a', short_name: 'Student_16dc368a' } },
    ],
    [
      'free-text keys are scrubbed only when the value is a string',
      { id: 1, message: { body: 'a@b.com', x: 'a@b.com' }, comment: 5, comments: ['a@b.com'] },
      { id: 1, message: { body: '[EMAIL_REDACTED]', x: 'a@b.com' }, comment: 5, comments: ['a@b.com'] },
    ],
    [
      'user-only null fields follow the container, not the key',
      { participant: { id: 4, address: '1 Main', locale: 'en' }, address: 'HQ' },
      { participant: { id: 4, address: null, locale: null }, address: 'HQ' },
    ],
  ])('scrubIdentity: %s', (_label, input, expected) => {
    expect(scrubIdentity(input, fresh())).toEqual(expected);
  });
});

// ---------------------------------------------------------------------------
// Live leak regressions (upstream issue #166)
// ---------------------------------------------------------------------------

describe('nested identity fields', () => {
  it('scrubs identity nested in enrollments', () => {
    const result = anonymizeResponseData(usersWithEnrollments(), 'users', fresh());
    expectNoPii(result);

    const user = result[0];
    const enrollment = user.enrollments[0];
    expect(enrollment.sis_user_id).toBeNull();
    expect(enrollment.user.name).toMatch(/^Student_/);
    expect(enrollment.user.login_id).toBe(user.login_id);
    // Ids are preserved for functionality.
    expect(user.id).toBe(101);
    expect(enrollment.user.id).toBe(101);
    expect(enrollment.type).toBe('StudentEnrollment');
  });

  it('scrubs submission comment authors', () => {
    const result = anonymizeResponseData(submissionsWithComments(), 'submissions', fresh());
    expectNoPii(result);

    const comment = result[0].submission_comments[0];
    expect(comment.author_name).toMatch(/^Student_/);
    expect(comment.author.display_name).toBe(comment.author_name);
    expect(comment.author.avatar_image_url).toBeNull();
    expect(comment.comment).toContain('[EMAIL_REDACTED]');
    expect(comment.comment).toContain('[PHONE_REDACTED]');
    // Author id preserved so peer-review analytics still work.
    expect(comment.author_id).toBe(202);
  });

  it('scrubs a full rubric assessment', () => {
    const result = anonymizeResponseData(rubricAssessmentSubmission(), 'submissions', fresh());
    expectNoPii(result);

    const assessment = result.full_rubric_assessment;
    expect(assessment.assessor_name).toMatch(/^Student_/);
    expect(assessment.assessor.display_name).toBe(assessment.assessor_name);
    expect(assessment.data[0].comments).toContain('[EMAIL_REDACTED]');
    expect(assessment.data[0].points).toBe(4);
  });

  it('gives submitter and reviewer different pseudonyms', () => {
    const pseudonyms = fresh();
    const result = anonymizeResponseData(submissionsWithComments(), 'submissions', pseudonyms);
    expect(result[0].submission_comments[0].author_name).toBe(generateAnonymousId(202, 'Student', pseudonyms));
    expect(generateAnonymousId(202, 'Student', pseudonyms)).not.toBe(generateAnonymousId(101, 'Student', pseudonyms));
  });
});

describe('discussion /view wrapper', () => {
  it('anonymizes view entries', () => {
    const entry = anonymizeResponseData(discussionView(), 'discussions', fresh()).view[0];
    expect(entry.user_name).toBe('Student_16dc368a');
    expect(entry.message).toBe('My email is [EMAIL_REDACTED]');
  });

  it('anonymizes nested replies', () => {
    const reply = anonymizeResponseData(discussionView(), 'discussions', fresh()).view[0].replies[0];
    expect(reply.user_name).not.toBe('Bob Learner');
    expect(reply.user_name).toMatch(/^Student_/);
  });

  it('anonymizes participants', () => {
    const result = anonymizeResponseData(discussionView(), 'discussions', fresh());
    const names = result.participants.map((p: Json) => p.display_name);
    expect(names).not.toContain('Alice Student');
    expect(names).not.toContain('Bob Learner');
    expect(result.participants[0].avatar_image_url).toBeNull();
  });

  it('anonymizes new_entries', () => {
    const entry = anonymizeResponseData(discussionView(), 'discussions', fresh()).new_entries[0];
    expect(entry.user_name).not.toBe('Bob Learner');
    expect(entry.user_name).toMatch(/^Student_/);
  });

  it('uses one pseudonym per student across the response', () => {
    const result = anonymizeResponseData(discussionView(), 'discussions', fresh());
    expect(result.view[0].replies[0].user_name).toBe(result.new_entries[0].user_name);
    expect(result.participants[1].display_name).toBe(result.new_entries[0].user_name);
  });
});

describe('enrollment records with a nested user', () => {
  it('anonymizes the nested user and fabricates nothing on the wrapper', () => {
    const enrollment = {
      id: 9001, // enrollment id, not a student id
      course_id: 123,
      type: 'StudentEnrollment',
      sis_user_id: '670001234',
      user: { id: 101, name: 'Alice Student', sortable_name: 'Student, Alice', login_id: 'alice1' },
    };
    // Upstream's anonymize_user_data: the record is treated as user context.
    const result: Json = scrubIdentity(enrollment, fresh(), { userContext: true });
    expect(result.user.name).not.toBe('Alice Student');
    expect(result.user.name).toMatch(/^Student_/);
    expect(result.user.id).toBe(101);
    expect(result).not.toHaveProperty('name');
    expect(result).not.toHaveProperty('email');
    expect(result.sis_user_id).toBeNull();
    expect(result.type).toBe('StudentEnrollment');
  });

  it('does not fabricate identity on a flat non-user record', () => {
    const result = scrubIdentity({ id: 9003, course_id: 123, type: 'StudentEnrollment' }, fresh(), { userContext: true });
    expect(result).toEqual({ id: 9003, course_id: 123, type: 'StudentEnrollment' });
  });

  it('anonymizes an enrollment list', () => {
    const enrollments = [{ id: 9002, user_id: 102, user: { id: 102, name: 'Bob Learner', login_id: 'bob2' } }];
    const result = anonymizeResponseData(enrollments, 'users', fresh());
    expect(result[0]!.user.name).not.toBe('Bob Learner');
  });
});

// ---------------------------------------------------------------------------
// Structural invariants
// ---------------------------------------------------------------------------

describe('anonymization never adds a key', () => {
  it.each(FIXTURE_NAMES)('%s keeps every key set', (name) => {
    const result = anonymizeResponseData(fixture(name), 'submissions', fresh());
    expect(collectKeySets(result)).toEqual(collectKeySets(fixture(name)));
  });

  it.each<[string, () => Json, string]>([
    ['conversations', conversationsList, '/conversations'],
    ['pages', pagesList, '/pages'],
    ['discussion view', discussionView, '/courses/1/discussion_topics/2/view'],
    ['roster', usersWithEnrollments, '/courses/1/users'],
  ])('%s keeps every key set through its endpoint tier', (_label, build, path) => {
    expect(collectKeySets(anonymizeForEndpoint(build(), path).result)).toEqual(collectKeySets(build()));
  });

  it('a minimal user gains no fabricated fields', () => {
    const result = scrubIdentity({ id: 101, name: 'John Doe', login_id: 'jdoe2' }, fresh());
    expect(Object.keys(result).sort()).toEqual(['id', 'login_id', 'name']);
  });

  it('a record without content fields gains none from the submission refinement', () => {
    const result = anonymizeResponseData({ id: 1, user_id: 101, submitted_at: 'x' }, 'submissions', fresh());
    expect(Object.keys(result)).toEqual(['id', 'user_id', 'submitted_at']);
  });

  it('keeps a "__proto__" key as an ordinary own property', () => {
    const payload = JSON.parse('{"id": 101, "login_id": "jdoe2", "__proto__": {"email": "jdoe2@illinois.edu"}}');
    const result: Json = scrubIdentity(payload, fresh());
    expect(Object.getPrototypeOf(result)).toBe(Object.prototype);
    expect(Object.keys(result).sort()).toEqual(['__proto__', 'id', 'login_id']);
    expectNoPii(result);
    expect(JSON.parse(JSON.stringify(result)).__proto__.email).toBe('student_16dc368a@example.edu');
  });
});

describe('the input is never modified', () => {
  it.each<[string, () => Json, string]>([
    ['roster', usersWithEnrollments, '/courses/1/users'],
    ['submissions', submissionsWithComments, '/courses/1/assignments/2/submissions'],
    ['conversations', conversationsList, '/conversations'],
    ['pages', pagesList, '/courses/1/pages'],
  ])('%s', (_label, build, path) => {
    const input = build();
    anonymizeForEndpoint(input, path);
    expect(input).toEqual(build());
  });
});

describe('non-user objects keep their names', () => {
  it('preserves a bare name without a user signal', () => {
    const result = scrubIdentity({ id: 77, name: 'Project Teams', members_count: 4 }, fresh());
    expect(result).toEqual({ id: 77, name: 'Project Teams', members_count: 4 });
  });

  it('does not rewrite a course name', () => {
    const course = { id: 55, name: 'BADM 350 Fall 2026', course_code: 'BADM350' };
    expect(anonymizeResponseData(course, 'users', fresh()).name).toBe('BADM 350 Fall 2026');
  });

  it('does not treat a course with an enrollments list as a user', () => {
    const course = {
      id: 55,
      name: 'BADM 350 Fall 2026',
      course_code: 'BADM350',
      enrollments: [{ type: 'teacher', role: 'TeacherEnrollment' }],
    };
    expect(anonymizeResponseData(course, 'users', fresh()).name).toBe('BADM 350 Fall 2026');
  });

  it('a non-user marker beats user context', () => {
    const payload = { user: { id: 55, name: 'BADM 350', sis_course_id: 'X', time_zone: 'America/Chicago' } };
    expect(scrubIdentity(payload, fresh())).toEqual(payload);
  });

  it('preserves an attachment filename', () => {
    const submission = { id: 7003, user_id: 101, attachments: [{ id: 88, display_name: 'essay.pdf', size: 1024 }] };
    expect(scrubIdentity(submission, fresh()).attachments[0]!.display_name).toBe('essay.pdf');
  });

  it('preserves a calendar event location address', () => {
    const event = {
      id: 4001,
      title: 'Office Hours',
      location_name: 'Wohlers Hall',
      location_address: '1206 S Sixth St, Champaign IL',
      start_at: '2026-03-01T15:00:00Z',
    };
    expect(anonymizeResponseData(event, 'general', fresh())).toEqual(event);
  });

  it('preserves an address on a non-user record', () => {
    const account = { id: 1, name: 'Gies College of Business', address: '515 E Gregory Dr', workflow_state: 'active' };
    expect(anonymizeResponseData(account, 'general', fresh())).toEqual(account);
  });

  it('preserves unique_id on a non-person record', () => {
    const tool = { id: 77, name: 'Gradescope', unique_id: 'lti_gradescope_v2', workflow_state: 'public' };
    expect(anonymizeResponseData(tool, 'general', fresh())).toEqual(tool);
  });

  it('preserves full_name on a non-person record', () => {
    const outcomeGroup = { id: 9, full_name: 'Program Outcomes > Analytics', context_type: 'Course' };
    expect(anonymizeResponseData(outcomeGroup, 'general', fresh())).toEqual(outcomeGroup);
  });

  it('preserves a course time zone', () => {
    const course = { id: 12, name: 'BADM 350 Fall 2026', course_code: 'BADM350', time_zone: 'America/Chicago' };
    expect(anonymizeResponseData(course, 'general', fresh())).toEqual(course);
  });

  it('preserves a non-avatar URL', () => {
    const record = { id: 5, html_url: 'https://canvas/courses/1/users/101' };
    expect(anonymizeResponseData(record, 'general', fresh())).toEqual(record);
  });
});

describe('user-only null fields and avatar variants', () => {
  it('nulls time_zone and locale on a user', () => {
    const user = { id: 101, name: 'Jane Doe', sortable_name: 'Doe, Jane', time_zone: 'America/Chicago', locale: 'en' };
    const result: Json = anonymizeResponseData(user, 'users', fresh());
    expect(result.time_zone).toBeNull();
    expect(result.locale).toBeNull();
  });

  it.each(['avatar_url', 'avatar_image_url', 'assessor_avatar_url', 'avatar_path', 'Avatar_Image_URL'])(
    'nulls the avatar variant %s',
    (key) => {
      const record = { id: 101, user_id: 101, [key]: 'https://canvas/avatars/101' };
      expect(anonymizeResponseData(record, 'submissions', fresh())[key]).toBeNull();
    },
  );
});

// ---------------------------------------------------------------------------
// Typed refinements
// ---------------------------------------------------------------------------

describe('data type routing', () => {
  it('an explicit data type suppresses duck-typing', () => {
    // An assignment carrying a `message` key is not a discussion, and its
    // long description is still replaced.
    const assignment = {
      id: 42,
      name: 'Reflection Essay',
      due_at: '2026-03-01T23:59:00Z',
      message: 'See instructions',
      description: 'x'.repeat(1200),
    };
    const result = anonymizeResponseData(assignment, 'assignments', fresh());
    expect(result.description).toBe('[LONG_DESCRIPTION_REDACTED_FOR_PRIVACY]');
    expect(result.name).toBe('Reflection Essay');
  });

  it('the users type does not redact submission content', () => {
    const record = { id: 1, user_id: 101, submitted_at: '2026-03-01T00:00:00Z', body: 'hello' };
    expect(anonymizeResponseData(record, 'users', fresh()).body).toBe('hello');
  });

  it('an unknown data type falls back to duck-typing', () => {
    const record = { id: 1, user_id: 101, submitted_at: '2026-03-01T00:00:00Z', body: 'hello' };
    expect(anonymizeResponseData(record, 'general', fresh()).body).toBe('[CONTENT_REDACTED_FOR_Student_16dc368a]');
    expect(anonymizeResponseData(record, 'test_endpoint', fresh()).body).toBe('[CONTENT_REDACTED_FOR_Student_16dc368a]');
  });

  it('duck-typing prefers submitted_at, then due_at', () => {
    const both = { id: 1, user_id: 101, submitted_at: null, due_at: null, body: 'hi', description: 'x'.repeat(1001) };
    const result = anonymizeResponseData(both, 'general', fresh());
    expect(result.body).toBe('[CONTENT_REDACTED_FOR_Student_16dc368a]');
    expect(result.description).toHaveLength(1001);
  });
});

describe('submission content redaction', () => {
  it('redacts body and url per student and attachments generically', () => {
    const submission = {
      id: 7003,
      user_id: 101,
      body: 'My essay',
      url: 'https://example.com/my-work',
      attachments: [{ id: 88, display_name: 'essay.pdf' }],
    };
    expect(anonymizeResponseData(submission, 'submissions', fresh())).toEqual({
      id: 7003,
      user_id: 101,
      body: '[CONTENT_REDACTED_FOR_Student_16dc368a]',
      url: '[CONTENT_REDACTED_FOR_Student_16dc368a]',
      attachments: '[CONTENT_REDACTED]',
    });
  });

  it('leaves empty content fields as they are', () => {
    const submission = { id: 7003, user_id: 101, attachments: [], url: '', body: null };
    expect(anonymizeResponseData(submission, 'submissions', fresh())).toEqual(submission);
  });

  it('skips a record whose user_id is missing or falsy', () => {
    expect(anonymizeResponseData({ user_id: 0, submitted_at: 'x', body: 'hello a@b.com' }, 'submissions', fresh())).toEqual({
      user_id: 0,
      submitted_at: 'x',
      body: 'hello [EMAIL_REDACTED]',
    });
    expect(anonymizeResponseData({ id: 1, body: 'hello' }, 'submissions', fresh())).toEqual({ id: 1, body: 'hello' });
  });

  it('keys the placeholder to a string user_id the same way', () => {
    const record = { id: 1, user_id: '101', submitted_at: 'x', body: 'hi' };
    expect(anonymizeResponseData(record, 'general', fresh()).body).toBe('[CONTENT_REDACTED_FOR_Student_16dc368a]');
  });

  it('applies to records in nested lists but not to records nested inside a record', () => {
    const record = { id: 1, user_id: 101, submitted_at: 'x', body: 'hi' };
    expect(anonymizeResponseData([[record]], 'general', fresh())[0]![0]!.body).toBe(
      '[CONTENT_REDACTED_FOR_Student_16dc368a]',
    );
    // Upstream refines top-level records only; the nested body still gets the free-text scrub.
    const grouped = [{ user_id: 101, submissions: [{ ...record, body: 'my essay a@b.com' }] }];
    expect(anonymizeResponseData(grouped, 'submissions', fresh())[0]!.submissions[0]!.body).toBe(
      'my essay [EMAIL_REDACTED]',
    );
  });

  it('redacts another student’s submission but the gate exempts the caller’s own', () => {
    const submission = {
      id: 7004,
      user_id: 101,
      submitted_at: '2026-03-01T12:00:00Z',
      body: 'My own essay text',
      url: 'https://example.com/my-work',
    };
    const own = anonymizeForEndpoint(submission, '/courses/1/assignments/2/submissions/self');
    expect(own.tier).toBe('none');
    expect(own.result).toBe(submission);

    const other = anonymizeForEndpoint(submission, '/courses/1/assignments/2/submissions/101');
    expect(other.result.body).toBe('[CONTENT_REDACTED_FOR_Student_16dc368a]');
    expect(other.result.url).toBe('[CONTENT_REDACTED_FOR_Student_16dc368a]');
  });
});

describe('long assignment description redaction', () => {
  const describedBy = (description: unknown): Json =>
    anonymizeResponseData({ id: 1, due_at: null, description }, 'assignments', fresh()).description;

  it('replaces a description longer than 1000 characters', () => {
    expect(describedBy('x'.repeat(1001))).toBe('[LONG_DESCRIPTION_REDACTED_FOR_PRIVACY]');
  });

  it('keeps a description of exactly 1000 characters', () => {
    expect(describedBy('x'.repeat(1000))).toBe('x'.repeat(1000));
  });

  it('counts code points like Python, not UTF-16 units', () => {
    // 600 emoji are 1200 UTF-16 units but 600 characters.
    expect(describedBy('😀'.repeat(600))).toBe('😀'.repeat(600));
    expect(describedBy('😀'.repeat(1001))).toBe('[LONG_DESCRIPTION_REDACTED_FOR_PRIVACY]');
    expect(describedBy(`${'x'.repeat(999)}😀`)).toBe(`${'x'.repeat(999)}😀`);
    expect(describedBy(`${'x'.repeat(1000)}😀`)).toBe('[LONG_DESCRIPTION_REDACTED_FOR_PRIVACY]');
  });

  it('ignores non-string descriptions and other data types', () => {
    expect(describedBy(null)).toBeNull();
    expect(describedBy(['x'.repeat(2000)])).toEqual(['x'.repeat(2000)]);
    const record = { id: 3, description: 'x'.repeat(1001) };
    expect(anonymizeResponseData(record, 'general', fresh()).description).toHaveLength(1001);
    expect(anonymizeResponseData(record, 'users', fresh()).description).toHaveLength(1001);
  });
});

// ---------------------------------------------------------------------------
// Fail-closed behaviour
// ---------------------------------------------------------------------------

describe('unrecognized shapes are still scrubbed', () => {
  it('scrubs identity in an unknown shape', () => {
    const payload = {
      meta: { page: 1 },
      records: [
        {
          wrapper_id: 9,
          person: { id: 101, sortable_name: 'Doe, John', email: 'jdoe2@illinois.edu', sis_user_id: '670001234' },
        },
      ],
    };
    const result = anonymizeResponseData(payload, 'something_new', fresh());
    expectNoPii(result);
    expect(result.meta.page).toBe(1);
  });

  it('scrubs deeply nested identity', () => {
    const payload = { a: { b: { c: [{ user: { id: 101, name: 'Alice Example', login_id: 'jdoe2' } }] } } };
    expectNoPii(anonymizeResponseData(payload, 'general', fresh()));
  });

  it('passes primitives and empty containers through', () => {
    for (const value of [null, 5, 'a@b.com', true, [], {}]) {
      expect(anonymizeResponseData(value, 'general', fresh())).toEqual(value);
    }
  });

  it('treats a tier it does not recognise as full', () => {
    const bogus = 'strict' as string as AnonymizationTier;
    const result = anonymizeResponse(usersWithEnrollments(), { tier: bogus, path: '/courses/1/users', ...fresh() });
    expectNoPii(result);
    expect(result[0].name).toBe('Student_16dc368a');
  });
});

// ---------------------------------------------------------------------------
// Idempotence
// ---------------------------------------------------------------------------

describe('idempotence', () => {
  const cases: Array<[string, string]> = FIXTURE_NAMES.flatMap((name) =>
    ['users', 'submissions', 'discussions', 'assignments', 'general'].map((dataType): [string, string] => [name, dataType]),
  );

  it.each(cases)('%s as %s is a fixed point', (name, dataType) => {
    const once = anonymizeResponseData(fixture(name), dataType, fresh());
    expect(anonymizeResponseData(once, dataType, fresh())).toEqual(once);
  });

  it.each(FIXTURE_NAMES)('scrubIdentity on %s is a fixed point under every flag combination', (name) => {
    for (const scrubText of [true, false]) {
      for (const scrubDisplayNames of [true, false]) {
        const once = scrubIdentity(fixture(name), fresh(), { scrubText, scrubDisplayNames });
        expect(scrubIdentity(once, fresh(), { scrubText, scrubDisplayNames })).toEqual(once);
      }
    }
  });

  it.each<[string, () => Json, string]>([
    ['conversations list', conversationsList, '/conversations'],
    ['one conversation', conversationsList, '/conversations/6001'],
    ['pages', pagesList, '/courses/55/pages'],
    ['roster', usersWithEnrollments, '/courses/55/users'],
    ['profile', selfProfile, '/users/456/profile'],
    ['discussion view', discussionView, '/courses/55/discussion_topics/9/view'],
  ])('%s is a fixed point of its endpoint tier', (_label, build, path) => {
    const once = anonymizeForEndpoint(build(), path);
    const twice = anonymizeForEndpoint(once.result, path);
    expect(twice.tier).toBe(once.tier);
    expect(twice.result).toEqual(once.result);
  });

  it('is a fixed point when salted', () => {
    const once = anonymizeResponseData(usersWithEnrollments(), 'users', fresh('pepper'));
    expect(anonymizeResponseData(once, 'users', fresh('pepper'))).toEqual(once);
    expectNoPii(once);
  });

  it('does not re-label an already redacted attachment list', () => {
    // Upstream turns "[CONTENT_REDACTED]" into the per-student form on a second
    // pass; here the first-pass output is final.
    const submission = { id: 1, user_id: 101, submitted_at: 'x', body: 'hi', url: 'http://x', attachments: [{ id: 1 }] };
    const once = anonymizeResponseData(submission, 'submissions', fresh());
    expect(once.attachments).toBe('[CONTENT_REDACTED]');
    expect(anonymizeResponseData(once, 'submissions', fresh())).toEqual(once);
  });
});

// ---------------------------------------------------------------------------
// Field coverage found by upstream's #179 audit
// ---------------------------------------------------------------------------

describe('profile field coverage', () => {
  const paths: Array<Array<string | number>> = [
    ['primary_email'],
    ['unconfirmed_email'],
    ['contact_info'],
    ['full_name'],
    ['pronunciation'],
    ['communication_channels', 0, 'address'],
    ['pseudonyms', 0, 'unique_id'],
  ];
  const dig = (node: Json, path: Array<string | number>): Json => path.reduce((current, step) => current[step], node);

  it.each(paths.map((path): [string, Array<string | number>] => [path.join('.'), path]))('%s is rewritten', (_label, path) => {
    const after = dig(anonymizeResponseData(selfProfile(), 'users', fresh()), path);
    expect(after).not.toEqual(dig(selfProfile(), path));
    expect(JSON.stringify(after)).not.toContain('jdoe2');
    expect(JSON.stringify(after)).not.toContain('illinois.edu');
  });

  it.each(['primary_email', 'unconfirmed_email', 'contact_info'])('%s stays email-shaped', (key) => {
    const result: Json = scrubIdentity({ id: 101, sortable_name: 'Doe, John', [key]: 'jdoe2@illinois.edu' }, fresh());
    expect(result[key]).toBe('student_16dc368a@example.edu');
  });

  it('pseudonymises full_name on a user record', () => {
    const result = scrubIdentity({ id: 101, sortable_name: 'Doe, John', full_name: 'John Doe' }, fresh());
    expect(result.full_name).toBe('Student_16dc368a');
  });

  it('nulls pronunciation rather than pseudonymising it', () => {
    const result: Json = scrubIdentity({ id: 101, sortable_name: 'Doe, John', pronunciation: 'JON DOH' }, fresh());
    expect(result.pronunciation).toBeNull();
  });

  it('nulls communication channel addresses and keeps the channel type', () => {
    const result = anonymizeResponseData(selfProfile(), 'users', fresh());
    for (const channel of result.communication_channels) {
      expect(channel.address).toBeNull();
      expect(['email', 'sms']).toContain(channel.type);
    }
  });

  it('leaves no real address anywhere', () => {
    const result = anonymizeResponseData(selfProfile(), 'users', fresh());
    expectNoPii(result);
    for (const fragment of JSON.stringify(result).split('"')) {
      if (fragment.includes('@')) {
        expect(fragment.endsWith('@example.edu'), `stray address: ${fragment}`).toBe(true);
      }
    }
  });
});

// ---------------------------------------------------------------------------
// Endpoint tiers
// ---------------------------------------------------------------------------

describe('free_text tier on conversations', () => {
  const scrubbed = (): Json => {
    const { result, tier } = anonymizeForEndpoint(conversationsList(), '/conversations');
    expect(tier).toBe('free_text');
    return result[0];
  };

  it('redacts email and phone from the message preview', () => {
    const conversation = scrubbed();
    expect(conversation.last_message).not.toContain('jdoe2@illinois.edu');
    expect(conversation.last_message).toContain('[EMAIL_REDACTED]');
    expect(conversation.last_message).toContain('[PHONE_REDACTED]');
  });

  it('redacts email from the message body', () => {
    expect(scrubbed().messages[0].body).toContain('[EMAIL_REDACTED]');
  });

  it('keeps participant names', () => {
    const participant = scrubbed().participants[1];
    expect(participant.name).toBe('Carol Cee');
    expect(participant.full_name).toBe('Carol Cee');
  });

  it('still nulls direct identifiers', () => {
    const participant = scrubbed().participants[0];
    expect(participant.pronouns).toBeNull();
    expect(participant.avatar_url).toBeNull();
    expect(scrubbed().participants[1].pronouns).toBeNull();
  });

  it('keeps conversation metadata', () => {
    const conversation = scrubbed();
    expect(conversation.subject).toBe('Extension request');
    expect(conversation.workflow_state).toBe('unread');
    expect(conversation.last_authored_message).toBe('Sure - see you at office hours.');
  });
});

describe('identity tier on pages', () => {
  const scrubbed = (): Json => {
    const { result, tier } = anonymizeForEndpoint(pagesList(), '/courses/55/pages');
    expect(tier).toBe('identity');
    return result[0];
  };

  it('pseudonymises last_edited_by and keeps the id', () => {
    const editor = scrubbed().last_edited_by;
    expect(editor.display_name).toBe('Student_8bd9c0d4');
    expect(editor.id).toBe(303);
    expect(editor.avatar_image_url).toBeNull();
  });

  it('leaves the page body and metadata untouched', () => {
    const page = scrubbed();
    expect(page.body).toBe(pagesList()[0].body);
    expect(page.body).toContain('prof@illinois.edu');
    expect(page.title).toBe('Week 1 Overview');
    expect(page.url).toBe('week-1-overview');
    expect(page.published).toBe(true);
  });

  it('skips the typed refinements', () => {
    // A page-shaped record that would duck-type as a submission under `full`.
    const record = { id: 1, user_id: 101, submitted_at: 'x', body: 'kept', description: 'x'.repeat(1500), due_at: null };
    const result = anonymizeResponse(record, { tier: 'identity', path: '/courses/1/pages', ...fresh() });
    expect(result).toEqual(record);
  });
});

describe('the none tier', () => {
  it('returns the payload itself, unscrubbed', () => {
    const profile = selfProfile();
    const { result, tier } = anonymizeForEndpoint(profile, '/users/self/profile');
    expect(tier).toBe('none');
    expect(result).toBe(profile);
    expect(result.name).toBe('John Doe');
  });
});

describe('the two scrub flags are independent', () => {
  const record = (): Json => ({ id: 101, sortable_name: 'Doe, John', name: 'John Doe', body: 'Mail jdoe2@illinois.edu' });

  it('scrubs both by default', () => {
    const result = scrubIdentity(record(), fresh());
    expect(result.name).toMatch(/^Student_/);
    expect(result.body).toContain('[EMAIL_REDACTED]');
  });

  it('scrubText: false keeps only the body', () => {
    const result = scrubIdentity(record(), fresh(), { scrubText: false });
    expect(result.name).toMatch(/^Student_/);
    expect(result.body).toBe('Mail jdoe2@illinois.edu');
  });

  it('scrubDisplayNames: false keeps only the name', () => {
    const result = scrubIdentity(record(), fresh(), { scrubDisplayNames: false });
    expect(result.name).toBe('John Doe');
    expect(result.body).toContain('[EMAIL_REDACTED]');
  });

  it('strict and null fields apply under every flag combination', () => {
    const user = {
      id: 101,
      sortable_name: 'Doe, John',
      short_name: 'John',
      email: 'jdoe2@illinois.edu',
      login_id: 'jdoe2',
      sis_user_id: '670001234',
      avatar_url: 'https://canvas/avatars/101',
      pronouns: 'he/him',
    };
    for (const options of [{ scrubText: false }, { scrubDisplayNames: false }, { scrubText: false, scrubDisplayNames: false }]) {
      const result: Json = scrubIdentity(user, fresh(), options);
      expectNoPii(result);
      expect(result.sis_user_id).toBeNull();
      expect(result.avatar_url).toBeNull();
      expect(result.pronouns).toBeNull();
      expect(result.email).toBe('student_16dc368a@example.edu');
    }
  });

  it('flags propagate through nesting', () => {
    const payload = {
      a: [{ b: { user: { id: 101, login_id: 'jdoe2', name: 'John Doe', body: 'Mail jdoe2@illinois.edu' } } }],
    };
    const user = scrubIdentity(payload, fresh(), { scrubText: false, scrubDisplayNames: false }).a[0]!.b.user;
    expect(user.name).toBe('John Doe');
    expect(user.body).toBe('Mail jdoe2@illinois.edu');
    expect(user.login_id).toBe('student_16dc368a');
  });

  it('a bare-string user container follows the name flag', () => {
    const bare = { id: 1, user_id: 1, author: 'Bob Smith' };
    expect(scrubIdentity(bare, fresh(), { scrubDisplayNames: false }).author).toBe('Bob Smith');
    expect(scrubIdentity(bare, fresh()).author).toBe('Student_6b86b273');
  });

  it('inheritedId keys a record without an id to an enclosing user', () => {
    const result = scrubIdentity({ display_name: 'essay.pdf', author_name: 'John Doe' }, fresh(), { inheritedId: 101 });
    // display_name is ambiguous and this record carries no user signal of its own.
    expect(result).toEqual({ display_name: 'essay.pdf', author_name: 'Student_16dc368a' });
  });
});

// ---------------------------------------------------------------------------
// Salted pseudonyms through the scrubber
// ---------------------------------------------------------------------------

describe('salted scrubbing', () => {
  it('uses the HMAC pseudonym everywhere and never the unsalted one', () => {
    const path = '/courses/55/assignments/42/submissions';
    const result = anonymizeResponse(submissionsWithComments(), { tier: tierForPath(path), path, ...fresh('pepper') });
    expectNoPii(result);
    expect(result[0].body).toBe('[CONTENT_REDACTED_FOR_Student_a3f1a1b9]');
    expect(JSON.stringify(result)).not.toContain('16dc368a');
    expect(JSON.stringify(result)).not.toContain('c17edaae');
  });

  it('fills the caller’s memo, one entry per distinct student', () => {
    const pseudonyms = fresh('pepper');
    anonymizeResponse(submissionsWithComments(), { tier: 'full', path: '/courses/1/assignments/2/submissions', ...pseudonyms });
    expect([...pseudonyms.memo.keys()].sort()).toEqual(['Student:101', 'Student:202']);
  });
});
